ALTER TABLE channels ADD COLUMN type INTEGER NOT NULL DEFAULT 1;
ALTER TABLE channels ADD COLUMN group_name TEXT;
ALTER TABLE channels ADD COLUMN priority INTEGER NOT NULL DEFAULT 0;
ALTER TABLE channels ADD COLUMN metadata_json TEXT;
ALTER TABLE channels ADD COLUMN test_time INTEGER;
ALTER TABLE channels ADD COLUMN response_time_ms INTEGER;
